version: "3.4"

services:
  nginx:
    container_name: nginx
    image: NGINX_DOCKER_IMAGE
    ports:
      - 80:80
    # volumes:
    #   - ./public:/var/www/html/public
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - web-network

  php:
    container_name: php
    image: PHP_DOCKER_IMAGE
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
