name: PHP QC Build & Deploy

on:
  push:
    branches:
      - main
      - feature/building-dockers
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  job-tag:
    runs-on: ubuntu-latest
    outputs:
      output-tag: ${{ steps.get-tag.outputs.tag }}
      output-clean-tag: ${{ steps.get-tag.outputs.clean-tag }}
      output-branch: ${{ steps.get-branch.outputs.branch }}
      output-clean-branch: ${{ steps.get-branch.outputs.clean-branch }}
    steps:
      - id: get-tag
        run: |
          tag="${GITHUB_REF/refs\/tags\//}"
          cleanTag="${tag//\//-}"
          echo tag $tag
          echo cleanTag $cleanTag
          echo "::set-output name=tag::$(echo $tag)"
          echo "::set-output name=clean-tag::$(echo $cleanTag)"
      - id: get-branch
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          cleanBranch="${branch//\//-}"
          echo branch $branch
          echo cleanBranch $cleanBranch
          echo "::set-output name=branch::$(echo $branch)"
          echo "::set-output name=clean-branch::$(echo $cleanBranch)"

  build:
    needs: [test, job-tag]
    uses: ./.github/workflows/build-common.yml
    with:
      ref: ${{ needs.job-tag.outputs.output-branch }}
      image_tag: latest
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    needs: [build, job-tag]
    uses: ./.github/workflows/deploy-common.yml
    with:
      ref: ${{ needs.job-tag.outputs.output-branch }}
      image_tag: latest
      target_env: ''
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      APP_SERVER_01_IP: ${{ secrets.APP_SERVER_01_IP }}
      BASTION_IP: ${{ secrets.BASTION_IP }}
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
